---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-deployment.yaml
  - 02-service.yaml
  - 03-drivetester-route.yaml
  - 04-www-drivetester-route.yaml
  - 05-pvc.yaml
